"""empty message

Revision ID: 2c3b7a0868df
Revises: d7cde6e39fd7
Create Date: 2022-11-09 03:33:43.279339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3b7a0868df'
down_revision = 'd7cde6e39fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_alert', sa.Boolean(), nullable=True),
    sa.Column('subscription_alert', sa.Boolean(), nullable=True),
    sa.Column('news_alert', sa.Boolean(), nullable=True),
    sa.Column('bots_report', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
