"""empty message

Revision ID: 303cb3992e79
Revises: 2c3b7a0868df
Create Date: 2022-11-09 04:56:22.071034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '303cb3992e79'
down_revision = '2c3b7a0868df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_time', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'last_ip')
    op.drop_column('user', 'last_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_ip', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_table('activity')
    # ### end Alembic commands ###
