"""empty message

Revision ID: aea219b1a438
Revises: c27255a8e1ab
Create Date: 2022-11-03 03:27:44.495289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea219b1a438'
down_revision = 'c27255a8e1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'time')
    # ### end Alembic commands ###
