"""empty message

Revision ID: d7cde6e39fd7
Revises: f3a857a1190f
Create Date: 2022-11-06 19:12:36.686653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cde6e39fd7'
down_revision = 'f3a857a1190f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.BigInteger(), nullable=True),
    sa.Column('open', sa.String(length=20), nullable=True),
    sa.Column('high', sa.String(length=20), nullable=True),
    sa.Column('low', sa.String(length=20), nullable=True),
    sa.Column('close', sa.String(length=20), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candlestick')
    # ### end Alembic commands ###
